<LoginScreen>:
    orientation: 'vertical'
    GridLayout:
        cols: 2
        Label:
            text: "Imie kierowcy"
            size_hint_y: 0.3
        TextInput:
            id: name
            size_hint_y: 0.3
        Label:
            text: "Nazwisko"
            size_hint_y: 0.3
        TextInput:
            id: last_name
            size_hint_y: 0.3
        Button:
            id: add
            size_hint_y: 0.3
            text: "Dodaj"
            on_release: root.input()
        Button:
            size_hint_y: 0.3
            id: check
            text: "Pokaz kierowcow"
            on_release: root.check()
    GridLayout:
        cols: 1
        id: grid
